test_that("front + primary flow writes a deck", {
  skip_if_officer_missing()
  testthat::skip_if_not_installed("ggplot2")
  skip_if_xml2_missing()

  cfg <- new_pia_template(template_fixture_path())
  x <- open_template(cfg)

  chart <- ggplot2::ggplot(ggplot2::mpg, ggplot2::aes(displ, hwy)) +
    ggplot2::geom_point()

  body_title <- paste0("Body Title ", as.integer(Sys.time()))
  x <- add_primary_slide(
    x = x,
    cfg = cfg,
    chart = chart,
    title = body_title,
    bullets = c("Point one", "Point two")
  )

  front_title <- paste0("Front Title ", as.integer(Sys.time()))
  x <- add_front_slide(
    x = x,
    cfg = cfg,
    title = front_title,
    subtitle = "Generated by tests"
  )

  out <- tempfile(fileext = ".pptx")
  write_presentation(x, out)
  expect_true(file.exists(out))
  expect_gt(file.info(out)$size, 0)

  first_text <- first_slide_text(out)
  expect_true(front_title %in% first_text)
})
